version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node
        environment:
          TZ: Asia/Shanghai
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: git clone https://github.com/fitzix/hexo-theme-apollo.git themes/apollo
      - run: cp themes/fitzix/apollo.yml themes/apollo/_config.yml

      - deploy:
          command: |
            git config --global user.email $GIT_EMAIL
            git config --global user.name $GIT_NAME
            yarn deploy

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          context: Github
          filters:
            branches:
              only: pages